Azure-Samples/contoso-real-estate

README.md
I've tested this flow out in Codespaces and everything successfully deployed. Would probably be worth having one other person try it out just to sanity check.
=> chore: update README to improve clarity for azd deployment

azure.yaml
Required for seeing deployment telemetry from azd
=> Add template metadata to azure.yaml

packages/api/README.md, packages/portal/README.md
=> docs: add readme files to packages

README.md
Simple call to action for additional visibility. Tested that it works and launches against Azure-Samples org Codespaces (if you are a member) or against user profile Codespaces (if not)
=> Add "Open In Codespaces" button

packages/portal/src/app/shared/card/card.component.html, packages/portal/src/app/shared/card/card.component.scss, packages/portal/src/app/shared/card/card.component.ts
=> feat(portal): Implement NgOptimizedImage directive

packages/portal/src/app/searchpage/searchpage.component.scss
* Fix form field styles that was broken with material migation
=> chore: fix form field(pending CORS)

packages/portal/src/app/about/about.component.ts, packages/portal/src/app/checkoutpage/checkoutpage.component.html, packages/portal/src/app/checkoutpage/checkoutpage.component.ts, packages/portal/src/app/profile/profile.component.html, packages/portal/src/app/profile/profile.component.ts, packages/portal/src/app/rentalpage/rentalpage.component.html, packages/portal/src/app/rentalpage/rentalpage.component.ts, packages/portal/src/app/searchpage/searchpage.component.html, packages/portal/src/app/searchpage/searchpage.component.ts, packages/portal/src/app/shared/booking-form/booking-form.component.html, packages/portal/src/app/shared/booking-form/booking-form.component.ts, packages/portal/src/app/shared/card/card.component.html, packages/portal/src/app/shared/card/card.component.ts, packages/portal/src/app/shared/errors/not-found/not-found.component.ts, packages/portal/src/app/shared/favorite-button/favorite-button/favorite-button.component.html, packages/portal/src/app/shared/favorite-button/favorite-button/favorite-button.component.ts, packages/portal/src/app/shared/main-nav/main-nav.component.html, packages/portal/src/app/shared/main-nav/main-nav.component.ts, packages/portal/src/app/shared/text-block/text-block.component.ts, packages/portal/src/types/index.d.ts
* PR from develop branch (codespace test)
=> chore(portal): use Angular Signals

.devcontainer/devcontainer.json
FIX: 
Add VS Code extension
Fixes #245
=> ci(testing): add PlayWright VSCode extension

.github/ISSUE_TEMPLATE/hack-together.md
Template to report issues for the Hack Together event
=> chore: create hack-together.md

infra/app/stripe.bicep
Fix for https://github.com/Azure-Samples/contoso-real-estate/issues/266
@dfberry can you test this branch to see if it fixes your issue?
I can't test it as I don't have a functional azd environment on my machine
=> chore(infra): make stripe keys optional

CONTRIBUTING.md
Fixes #294
Renamed bux to bug in contributing.md
=> fix: fixed typo in contrubuting.md

packages/portal/src/app/rentalpage/rentalpage.component.scss, packages/portal/src/app/shared/booking-form/booking-form.component.scss
I fixed the overflow of the listing page and its images. I made the overflow in the listing container scroll.
=> fix(portal): issue #260 fixed the responsive design for mobile in the 'view listing page'

packages/portal/src/app/shared/booking-form/booking-form.component.html, packages/portal/src/app/shared/booking-form/booking-form.component.scss
Fixes #252 Blurred Booking 
Solution:
- I added `[disabled]="isGuest()" ` to the affected `<input>` fields
- I added `pointer-events: none;` to `.filter-blur` scss
https://github.com/Azure-Samples/contoso-real-estate/assets/43810146/b882b89f-9c1d-4ea8-97cd-4acaabb32d5b
Again, I'm open to suggestions regarding other issues also I am open to other suggestions. :)
=> fix: fixed Blurred Booking Options Accessible #252

README.md, packages/api/README.md, packages/docs/README.md, packages/portal/README.md
All typos addressed in this issue #311 have been fixed.
Had come across some problems while making the PR , it was taking in previous commits as well. But I managed to get it fixed.
The Issue was very detailed, so it helped a lot in making the changes.
=> docs: fix typos in README files

packages/portal/src/app/authentication/authentication.component.scss
Fixes #279 Regarding the Sign-In Button Bug
Thanks @richardrigutins for the analysis and suggestions. I have incorporated your suggestion of using a more specific CSS selector to increase the priority in this PR.
@anfibiacreativa Thanks for reminding me about this PR
I have changed the CSS o be more specific by adding ```.button``` as suggested by Richard ```authentication.component.scss``` and it seems to be working!
If any changes are required, do let me know and thanks for the hacktogether program, really good for students who are starting out with their open-source journey.
https://github.com/Azure-Samples/contoso-real-estate/assets/43810146/2fb8e6d3-ad9e-46f8-8c42-29956a681b5c
=> fix: fixed sign-in buttons change background color after reloading the page 

packages/portal/src/app/shared/favorite-button/favorite-button/favorite-button.component.ts
I implement a batch call to the favorites call.
Now 
before 
PD: Im not to much into ts or angular , so maybe can be a better way to do this or pattern I mean usually i work as BackEnd in another languages and im not feel confident at all with this solution . Im open to do this in a different way.  Just here to improve and learn 📟 
it "solve " #167
=> chore: add batch call to get api/favorites

docs/README-scenario-5.md
=> fix(stripe): get env var

packages/portal/src/app/authentication/authentication.component.ts
Used this {StackOverflow](https://stackoverflow.com/questions/56005848/angular-how-to-set-default-values-for-optional-input-properties) to fix #360.
=> fix(portal): redirect auth

packages/portal/src/app/authentication/authentication.component.ts
=> fix(portal): social icons

infra/app/db.bicep
=> fix(db): remove/rename db and collections

.vscode/launch.json
=> fix(infra): vscode launch file

.devcontainer/devcontainer.json, .devcontainer/post-create-command.sh
=> fix(infra): azd dev container feature

packages/testing/e2e/models/home-page.ts
there is a misspelling word in home-page.ts file
=> fix: misspelling in home-page.ts

packages/api-v4/src/models/user.schema.ts, packages/api/models/user.schema.ts, packages/docs/website/docs/02-develop/scenario-3/0-intro.md, packages/portal/src/app/authentication/authentication.component.scss, packages/portal/src/app/authentication/authentication.component.ts
=> fix(portal): remove apple (portal, api, api-v4, docs)

packages/portal/src/environments/environment.prod.ts
=> fix: use blog and graphql uris in prod

packages/portal/package.json
=> fix: remove duplicate apollo-angular dep

infra/main.parameters.json
=> fix(infra): azd requires default values now to bypass user ask

.devcontainer/post-create-command.sh
=> fix(infra): add playwright deps to postCreateCommand script

README.md
#411 - @anfibiacreativa Once this is merged, I can onboard repo to samples browser.
=> fix(docs): samples browser metadata

.devcontainer/post-create-command.sh, package-lock.json
1) Fix issue #426
2) New package-lock.json for api-test license type
Video of container starting up - https://app.screencastify.com/v3/watch/P20bFhiffjhMLRmXZUVh
=> fix(devx): change the way playwright is installed

packages/api/local.settings.json
#414 - force push the local.settings.json so that project's `azd deploy` works without changes.
=> fix(api): add local.settings.json so add just works

.devcontainer/devcontainer.json, .devcontainer/post-create-command.sh, packages/api-v4/src/index.ts
This PR fixes devcontainer config and a bug in functions v4 where a function is registered with the same name twice.
=> fix: fix config and versions

README.md
=> docs: update main README.md with scenarios links

packages/notifications/README.md
Issue #451 
Readme instruction
Current output
Target output
=> fix: updated command for package installs for the notification server (ReadMe)
